export const PLUGIN_NAME = "opencode-auto-batch"
export const LEGACY_PLUGIN_NAME = "oh-my-opencode"
export const CONFIG_BASENAME = "oh-my-opencode"
export const LOG_FILENAME = "opencode-auto-batch.log"
export const CACHE_DIR_NAME = "opencode-auto-batch"
